### PR TITLE
Large icons

### PR DESCRIPTION
**Pull request by wmcoogan**
Add the large 1024 icons missing from the wallet and watch app targets.

### CODE REVIEW

**Comment by Stouse49** [comment]
Are the missing 1024px icons, the ones that Xcode complain about when we build the app for publishing?

**Comment by wmcoogan** [comment]
Not sure. Before my time. They were missing so I added them.

**Comment by wmcoogan** [comment]
I had to try a few iterations because every time I resized, it went
1024×1025. Eventually, I was able to change some parameters and got it
where it was happy with it

**Comment by Stouse49** [comment]
This is approved.

**Pull request merged**
